# permissions for end users to edit clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissuer-editor-role
rules:
- apiGroups:
  - hvca.globalsign.com
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hvca.globalsign.com
  resources:
  - clusterissuers/status
  verbs:
  - get
